### PR TITLE
Add more functions or contribute ideas

### PR DESCRIPTION
**Pull request by ajaysalunkhe16**
Created function isLengthThree() and handled exception.

### CODE REVIEW

**Review by JasonTurley — CHANGES_REQUESTED** [review]
Thank you for contributing. A few notes:
- Use lower_case_with_underscores for function names. 
- I think you want "==" not "="
- Add test cases to /tests/three.py

**Comment by ajaysalunkhe16** [comment]
> Thank you for contributing. A few notes:
> 
> * Use lower_case_with_underscores for function names.
> * I think you want "==" not "="
> * Add test cases to /tests/three.py

I did changes as above and added test case. Please take a look once. Thanks.

**Comment by ajaysalunkhe16** [comment]
@JasonTurley Please take a look at PR. Thank you.

**Comment by ajaysalunkhe16** [comment]
@JasonTurley will be grateful if you take a look at PR.

**Comment by JasonTurley** [comment]
Please don't spam requests for me to look over PRs.

**Review by JasonTurley — APPROVED** [review]

**Pull request merged**
